#!/usr/bin/env bash
# scaffold_app.sh — create the fresh Vite + React + TS replica app, wired for REAL backend data.
#
# Produces a clean app whose ONLY job is to render 1:1 legacy replicas, styled from the legacy theme,
# fed by REAL backend data in either of two modes (Copilot picks per screen via VITE_DATA_MODE):
#
#   record  (default) — MSW replays the REAL responses recorded into the HAR at capture time
#                       (handlers generated by capture_fixtures.py from responses.har). Exact parity.
#   live              — no MSW; Vite server.proxy forwards calls to the live backend (real-time data,
#                       real session cookies). Structure/style parity (live data drifts from the shot).
#
# No component library (would restyle and break "no new artifacts"). Plain CSS Modules + a global
# theme.css of legacy-derived CSS variables (from extract_theme.py).
#
# Usage:  bash scaffold_app.sh <target-dir> [path/to/theme.css]
#   env:  VITE_BACKEND (default http://127.0.0.1:8080)   VITE_PROXY_PATHS (default "/BAA,/api")
set -euo pipefail

[ "${1:-}" = "--check" ] && { command -v node >/dev/null && command -v npm >/dev/null && echo "scaffold_app: node/npm present" && exit 0 || { echo "scaffold_app: node/npm MISSING"; exit 1; }; }

TARGET="${1:-}"
THEME_SRC="${2:-}"
[ -z "$TARGET" ] && { echo "usage: scaffold_app.sh <target-dir> [theme.css]"; exit 1; }
if [ -e "$TARGET" ] && [ -n "$(ls -A "$TARGET" 2>/dev/null || true)" ]; then
  echo "refusing: '$TARGET' exists and is not empty"; exit 1
fi

echo ">> creating Vite React-TS app at $TARGET"
npm create vite@latest "$TARGET" -- --template react-ts
cd "$TARGET"

echo ">> installing deps (react app + MSW for record-mode HAR replay + pixel-diff tooling)"
npm install
npm i -D msw pixelmatch pngjs

echo ">> initializing MSW service worker into public/"
npx msw init public/ --save

echo ">> writing vite.config.ts with a live-backend proxy (used in VITE_DATA_MODE=live)"
cat > vite.config.ts <<'EOF'
import { defineConfig, loadEnv } from 'vite'
import react from '@vitejs/plugin-react'

// Live mode: proxy real backend calls (keeps cookies/session so REAL data renders, no fakes).
export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, process.cwd(), '')
  const backend = env.VITE_BACKEND || 'http://127.0.0.1:8080'
  const paths = (env.VITE_PROXY_PATHS || '/BAA,/api').split(',').map(s => s.trim()).filter(Boolean)
  const proxy = Object.fromEntries(paths.map(p => [p, {
    target: backend, changeOrigin: true, secure: false, cookieDomainRewrite: 'localhost',
  }]))
  return { plugins: [react()], server: { proxy } }
})
EOF

echo ">> writing data-layer wiring (src/mocks/*, record vs live)"
mkdir -p src/mocks src/screens
cat > src/mocks/handlers.ts <<'EOF'
// REAL-response replay (record mode). capture_fixtures.py converts each view's responses.har into
// src/mocks/<viewId>/handlers.ts — handlers that return the EXACT bytes the legacy backend returned
// (no hand-authored data). Collected here via Vite's import.meta.glob; no manual registration.
const mods = import.meta.glob('./*/handlers.ts', { eager: true }) as Record<string, { handlers?: unknown[] }>
export const handlers = Object.values(mods).flatMap(m => m.handlers ?? [])
EOF

cat > src/mocks/browser.ts <<'EOF'
import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'
export const worker = setupWorker(...handlers)
EOF

cat > src/api.ts <<'EOF'
// All data calls go through here so live mode keeps the backend session cookie.
// record mode: MSW intercepts and replays the recorded HAR responses.
// live mode:   Vite proxy forwards to the real backend; credentials carry the session.
export async function apiFetch(path: string, init: RequestInit = {}) {
  return fetch(path, { credentials: 'include', ...init })
}
EOF

echo ">> wiring data-mode bootstrap + global legacy theme into src/main.tsx"
cat > src/main.tsx <<'EOF'
import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.tsx'
import './index.css'
import './theme.css'   // legacy-derived CSS variables (extract_theme.py) — colors/fonts come from here

async function enableData() {
  // VITE_DATA_MODE: 'record' (default) replays REAL recorded responses via MSW; 'live' uses the Vite proxy.
  const mode = import.meta.env.VITE_DATA_MODE || 'record'
  if (mode !== 'record') return
  const { worker } = await import('./mocks/browser')
  await worker.start({ onUnhandledRequest: 'bypass' })
}

enableData().then(() => {
  createRoot(document.getElementById('root')!).render(
    <StrictMode><App /></StrictMode>,
  )
})
EOF

echo ">> seeding theme.css (legacy palette/fonts)"
if [ -n "$THEME_SRC" ] && [ -f "$THEME_SRC" ]; then
  cp "$THEME_SRC" src/theme.css
  echo "   copied theme from $THEME_SRC"
else
  echo "/* placeholder — run extract_theme.py and pass theme.css to scaffold_app.sh, or overwrite this */
:root { /* --color-01, --font-1, --fs-13 ... */ }" > src/theme.css
  echo "   wrote placeholder src/theme.css (no theme passed)"
fi

echo ">> seeding the Login screen (F000) — auth is real; its session feeds backend data calls"
mkdir -p src/screens/Login
cat > src/screens/Login/Login.tsx <<'EOF'
import { useState } from 'react'
// F000 Login — rebuild 1:1 from the captured login screen + its source-model.json.
// Posts the REAL login action so the established session authenticates subsequent data calls.
const LOGIN_ACTION = import.meta.env.VITE_LOGIN_ACTION || '/BAA/loginAction.do'
export default function Login({ onAuthed }: { onAuthed?: () => void }) {
  const [userId, setUserId] = useState('')
  const [password, setPassword] = useState('')
  async function submit(e: React.FormEvent) {
    e.preventDefault()
    await fetch(LOGIN_ACTION, {
      method: 'POST', credentials: 'include',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({ userId, password }),
    })
    onAuthed?.()
  }
  // TODO(builder): replace markup/labels/styles to match the captured login screen exactly.
  return (
    <form onSubmit={submit}>
      <input name="userId" value={userId} onChange={e => setUserId(e.target.value)} />
      <input name="password" type="password" value={password} onChange={e => setPassword(e.target.value)} />
      <button type="submit">Log in</button>
    </form>
  )
}
EOF

cat > src/App.tsx <<'EOF'
// Minimal shell. The builder adds one screen per iteration under src/screens/<Name>/ and routes by
// STATUS.md ID (hash route, e.g. #/f010). F000 Login is the first screen; its session enables data.
export default function App() {
  return (
    <div id="app-root">
      <p>jsp2react replica shell. Build screens under <code>src/screens/</code>; route by STATUS.md ID.</p>
    </div>
  )
}
EOF

echo ""
echo "DONE. Data modes (set per screen via STATUS.md / env):"
echo "  record (default):  python <…>/legacy-crawl-capture/scripts/capture_fixtures.py \\"
echo "        --har work/evidence/<view>/legacy.har --out src/mocks/<view>   # REAL responses -> handlers"
echo "        npm run dev"
echo "  live:              VITE_DATA_MODE=live VITE_BACKEND=http://127.0.0.1:8080 npm run dev   # real backend via proxy"
echo "  theme: colors/fonts come from src/theme.css (extract_theme.py). Build screens under src/screens/<Name>/."
