#!/usr/bin/env python3
"""
capture_fixtures.py — turn captured network traffic into MSW fixtures + handlers.

Input  : one or more <name>.network.json files produced by capture_screen.py.
Output : <out>/fixtures.json     — { "<METHOD> <pathname>": {status, content_type, body, query_seen[]} }
         <out>/handlers.ts       — MSW v2 handlers returning those fixtures (same endpoint paths).

This is what lets the React replica render the SAME data the legacy screenshot was taken with,
with NO live backend (non-negotiable: "renders faithfully on its own"). Same paths are wired, so
flipping MSW off later hits the real backend unchanged (data-wiring QA).

By default only data calls (xhr/fetch) become fixtures; the legacy HTML document response is the page
itself, not a data call the React app makes. Use --include-documents to keep them too.
Deterministic; no browser needed.
"""
import argparse, json, os, sys
from urllib.parse import urlsplit


def load_records(paths):
    recs = []
    for p in paths:
        try:
            data = json.load(open(p, encoding="utf-8"))
            recs.extend(data if isinstance(data, list) else data.get("network", []))
        except Exception as e:
            print(f"[warn] {p}: {e}", file=sys.stderr)
    return recs


def key_for(rec):
    u = urlsplit(rec.get("url", ""))
    return f'{rec.get("method","GET").upper()} {u.path}', u.query


def body_value(rec):
    body = rec.get("body")
    ct = rec.get("content_type", "")
    if body is None:
        return None, ct
    if "json" in ct:
        try:
            return json.loads(body), ct
        except Exception:
            return body, ct
    return body, ct  # text/xml/html kept as string


def ts_literal(v):
    """Embed a fixture value as a TS expression."""
    return json.dumps(v, ensure_ascii=False)


def main():
    ap = argparse.ArgumentParser(description="Build MSW fixtures + handlers from captured network.json files.")
    ap.add_argument("--network", nargs="+", required=True, help="One or more *.network.json files.")
    ap.add_argument("--out", required=True, help="Output directory (fixtures.json + handlers.ts).")
    ap.add_argument("--include-documents", action="store_true", help="Also fixture the top-level HTML document responses.")
    ap.add_argument("--self-check", action="store_true")
    args = ap.parse_args()

    if args.self_check:
        sample = [{"method": "GET", "url": "http://h/BAA/fateamprofile.do?fa=AB10", "status": 200,
                   "resource_type": "xhr", "content_type": "application/json", "body": '{"rows":[1,2]}'}]
        os.makedirs(args.out, exist_ok=True)
        fx = build(sample, False)
        assert "GET /BAA/fateamprofile.do" in fx, fx
        assert fx["GET /BAA/fateamprofile.do"]["body"] == {"rows": [1, 2]}
        print(json.dumps({"self_check": "ok", "keys": list(fx)}, indent=1))
        return

    recs = load_records(args.network)
    fixtures = build(recs, args.include_documents)
    os.makedirs(args.out, exist_ok=True)
    json.dump(fixtures, open(os.path.join(args.out, "fixtures.json"), "w", encoding="utf-8"), indent=1)
    open(os.path.join(args.out, "handlers.ts"), "w", encoding="utf-8").write(render_handlers(fixtures))
    print(json.dumps({"ok": True, "endpoints": len(fixtures), "out": args.out,
                      "keys": list(fixtures)[:20]}, indent=1))


def build(recs, include_documents):
    fixtures = {}
    for rec in recs:
        rt = rec.get("resource_type")
        if rt == "document" and not include_documents:
            continue
        key, query = key_for(rec)
        body, ct = body_value(rec)
        if key not in fixtures:
            fixtures[key] = {"status": rec.get("status", 200), "content_type": ct,
                             "body": body, "query_seen": []}
        if query and query not in fixtures[key]["query_seen"]:
            fixtures[key]["query_seen"].append(query)
    return fixtures


def render_handlers(fixtures):
    lines = [
        "// AUTO-GENERATED by capture_fixtures.py — MSW v2 handlers returning captured legacy data.",
        "// Same endpoint paths as the legacy app, so disabling MSW hits the real backend unchanged.",
        "import { http, HttpResponse } from 'msw'",
        "import fixtures from './fixtures.json'",
        "",
        "type Fx = { status: number; content_type: string; body: unknown }",
        "const fx = fixtures as Record<string, Fx>",
        "",
        "function respond(key: string) {",
        "  const f = fx[key]",
        "  if (!f) return HttpResponse.json({ error: 'no fixture: ' + key }, { status: 501 })",
        "  if (f.content_type && f.content_type.includes('json')) return HttpResponse.json(f.body as any, { status: f.status })",
        "  return new HttpResponse(f.body as any, { status: f.status, headers: { 'content-type': f.content_type || 'text/plain' } })",
        "}",
        "",
        "export const handlers = [",
    ]
    for key in fixtures:
        method, path = key.split(" ", 1)
        verb = method.lower()
        if verb not in ("get", "post", "put", "patch", "delete", "head", "options"):
            verb = "all"
        lines.append(f"  http.{verb}({ts_literal(path)}, () => respond({ts_literal(key)})),")
    lines.append("]")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    main()
